### ISSUE TITLE
Not working on Mac os x EI Capitan

### ISSUE THREAD

**Issue by vudn-job** [jbreeden/net-snmp2#8]
I got error:
dyld: lazy symbol binding failed: Symbol not found: _netsnmp_ds_set_boolean
  Referenced from: /usr/lib/libnetsnmp.dylib
  Expected in: flat namespace

dyld: Symbol not found: _netsnmp_ds_set_boolean
  Referenced from: /usr/lib/libnetsnmp.dylib
  Expected in: flat namespace

Trace/BPT trap: 5

Thanks in advance any support.

**Comment by jbreeden** [comment]
Did you happen to find a solution for this? I've just setup this project on my Linux machine again to investigate some of the other open issues. I can probably find a Mac to test it on as well, but I saw you had a PR so I'm thinking you may have resolved this already.

**Comment by dao-nguyen-vu** [comment]
Sorry, I forgot this issue. It take a bit time for reproducing.
I think pre-install net-snmp library in Mac was old version. Run `brew info net-snmp` for information
<img width="898" alt="screen shot 2018-05-23 at 2 19 49 pm" src="https://user-images.githubusercontent.com/13160702/40409817-2fbbcee4-5e96-11e8-97ec-64cef7d1033b.png">

After installing new version net-snmp from source (http://www.net-snmp.org), this error gone away.
Thanks.
